server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # VitePress cleanUrls
    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?|ttf|map)$ {
        expires 7d;
        add_header Cache-Control "public";
        try_files $uri =404;
    }

    # 禁止访问隐藏文件
    location ~ /\. {
        deny all;
    }
}
